#!/usr/bin/env bash

echo "== create bucket"

# exit immediately if any command returns a non-zero status
set -e

if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

aws s3api create-bucket \
--bucket $1 \
--create-bucket-configuration="LocationConstraint=us-east-2" \
--query Location \
--output text