#!/usr/bin/env bash

echo "== delete objects"

# exit immediately if any command returns a non-zero status
set -e

if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

aws s3api list-objects-v2 \
--bucket $1 \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $1 --delete file:///tmp/delete_objects.json