#!/usr/bin/env bash

echo "== list buckets"

# exit immediately if any command returns a non-zero status
set -e

# display top five results
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] | .Name'
echo "..."