#!/usr/bin/env bash

echo "== list objects"

# exit immediately if any command returns a non-zero status
set -e

if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

aws s3api list-objects-v2 --bucket $1